# Simple application configuration for testing
spring:
  application:
    name: microservices-common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ioedream
    username: root
    password: 123456

logging:
  level:
    root: INFO