---
apiVersion: v1
kind: Namespace
metadata:
  name: ioe-dream-staging
  labels:
    name: ioe-dream-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ioe-dream-production
  labels:
    name: ioe-dream-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ioe-dream-monitoring
  labels:
    name: ioe-dream-monitoring
    environment: monitoring